export type TCreator = {
  profile: string;
  fullName: any;
  email: string;
  password: any;
  phone: string;
  dateOfBirth: string;
  country: string;
  state: string;
  postalCode: string;
  city: string;
  street: string;
  houseBuildingNo: string;
  niche: string;
  language: string;
  profession: string;
  gender: string;
  ethnicity: string;
  bodyType: string;
  hairType: string;
  skinType: string;
  tiktokHandle: string;
  tiktokLink: string;
  instragramHandle: string;
  instragramLink: string;
  othersSocialLink: string;
  portfolioLink: string;
  ugcExampleVideo: {
    key: string;
    url: string;
  }[];
  introductionvideo: string;
  bankType: string;
  accountHolderName: string;
  accountNumber: string;
  swiftCode: string;
  bankName: string;
  iban: string;
  paypalEmail: string;
};
 